### PR TITLE
fix: add visualize.js to ignore list

### PR DESCRIPTION
**Pull request by xxryan1234**

### CODE REVIEW

**Comment by fakewaffle** [comment]
We don't want to get into the habit of ignoring specific files.

Is this a third-party dependency?

**Comment by iammary** [comment]
Yes @fakewaffle. This is for report generation using Jaspersoft. We temporarily added it using bower. Can we ask for a SINet repo for this instead?

**Comment by fakewaffle** [comment]
@iammary https://github.com/School-Improvement-Network/visualize.js

**Comment by iammary** [comment]
yay! thanks @fakewaffle

**Comment by fakewaffle** [comment]
Does that meet your needs? Are we good to close this with unmerged changes?

**Comment by xxryan1234** [comment]
Yes. this can be closed now @fakewaffle . Thanks

**Pull request closed without merging**
