### PR TITLE
add new eslint rules

### PR DESCRIPTION
**Pull request by fakewaffle**

### CODE REVIEW

**Comment by openam** [comment]
While you're doing the breaking change do you want to change to the newer version of JSCS?

**Comment by fakewaffle** [comment]
Yeah, probably should.

**Comment by openam** [comment]
We update the readme as well. https://github.com/School-Improvement-Network/coding-conventions/blame/master/readme.md#L30-L31

Should we state the versions of `eslint` and `jscs` that need to be installed?

**Comment by gideonairex** [comment]
@openam @fakewaffle is this GTG?

**Pull request merged**
